/**********************************************************************************************************************
 * \file main.c
 * \copyright Copyright (C) Infineon Technologies AG 2024
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "cy_pdl.h"
#include "cybsp.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/* Macro for DMA channel interrupt */
#define DMAC_CHANNEL_INTR               0x00000001u

/* Macro for DMA transfer size */
#define DMAC_TRANSFER_SIZE              16UL

/* DMA channel rrigger select line */
#define DMA_TRIGGER_SELECT              TRIG0_OUT_CPUSS_DMAC_TR_IN0

/* DMA Channel Trigger Group */
#define DMA_TRIGGER_ASSERT_CYCLES       CY_DMAC_RETRIG_4CYC

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/* Memory region. Data located in SRAM. */
const uint8_t g_region1Src[DMAC_TRANSFER_SIZE] = "PSoC4_HVMS-DMADC";
uint8_t g_region1Dst[DMAC_TRANSFER_SIZE] = {0UL};
const uint8_t g_region2Src[DMAC_TRANSFER_SIZE] = "PSoC4_HVMS-DMADC";
uint8_t g_region2Dst[DMAC_TRANSFER_SIZE] = {0UL};

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/**********************************************************************************************************************
 * Function Name: main
 * Summary:
 *  This is the main function.
 * Parameters:
 *  none
 * Return:
 *  int
 **********************************************************************************************************************/

int main(void)
{
    cy_rslt_t result;
    char srcdata1[16];
    char dstdata1[16];
    char srcdata2[16];
    char dstdata2[16];

    /* Initialize system */
    result = cybsp_init() ;
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }
    
    /* Enable global interrupts */
    __enable_irq();

    /* Allocate channel number to use with DMA functions. */
    Cy_DMAC_Channel_Init(USER_DMA_HW, USER_DMA_CHANNEL, &USER_DMA_channel_config);

    /* Configure descriptor 0 for memory region transfer. */
    Cy_DMAC_Descriptor_Init(USER_DMA_HW, USER_DMA_CHANNEL, CY_DMAC_DESCRIPTOR_PING, &USER_DMA_ping_config);
    Cy_DMAC_Descriptor_SetSrcAddress(USER_DMA_HW, USER_DMA_CHANNEL, CY_DMAC_DESCRIPTOR_PING, &g_region1Src);
    Cy_DMAC_Descriptor_SetDstAddress(USER_DMA_HW, USER_DMA_CHANNEL, CY_DMAC_DESCRIPTOR_PING, &g_region1Dst);

    /* Configure descriptor 1 for memory region transfer. */
    Cy_DMAC_Descriptor_Init(USER_DMA_HW, USER_DMA_CHANNEL, CY_DMAC_DESCRIPTOR_PONG, &USER_DMA_pong_config);
    Cy_DMAC_Descriptor_SetSrcAddress(USER_DMA_HW, USER_DMA_CHANNEL, CY_DMAC_DESCRIPTOR_PONG, &g_region2Src);
    Cy_DMAC_Descriptor_SetDstAddress(USER_DMA_HW, USER_DMA_CHANNEL, CY_DMAC_DESCRIPTOR_PONG, &g_region2Dst);

    /* Enable the DMA channel */
    Cy_DMAC_Channel_Enable(USER_DMA_HW, USER_DMA_CHANNEL);

    /* Enable DMA engine. */
    Cy_DMAC_Enable(USER_DMA_HW);

    /* Initialize with config set in peripheral and enable the UART to display the result*/
    Cy_SCB_UART_Init(UART_HW, &UART_config, NULL);
    Cy_SCB_UART_Enable(UART_HW);

    Cy_SCB_UART_PutString(UART_HW, "\x1b[2J\x1b[;H");
    Cy_SCB_UART_PutString(UART_HW, "************************************************************\r\n");
    Cy_SCB_UART_PutString(UART_HW, "DMA Data Transfer with Descriptor Chain \r\n");
    Cy_SCB_UART_PutString(UART_HW, "************************************************************\r\n\n");

    /* At this point both transfer descriptors are configured, the DMA channel
    * is enabled and waiting for a trigger.
    * 
    * Generate an SW trigger to initiate a transfer.
    */
    Cy_TrigMux_SwTrigger(DMA_TRIGGER_SELECT, DMA_TRIGGER_ASSERT_CYCLES);

    /* Wait until transfer is over */
    while (CY_DMAC_DONE == Cy_DMAC_Descriptor_GetResponse(USER_DMA_HW, USER_DMA_CHANNEL, CY_DMAC_DESCRIPTOR_PONG));

    /* Validate the transferred data */
    Cy_SCB_UART_PutString(UART_HW, "PING source = ");

    for(uint8_t i=0; i<DMAC_TRANSFER_SIZE; i++)
    {
        srcdata1[i] = g_region1Src[i];
        while (!Cy_SCB_UART_IsTxComplete(UART_HW));
        Cy_SCB_UART_Put(UART_HW, srcdata1[i]);
    }
    /* Validate the transferred data */
    Cy_SCB_UART_PutString(UART_HW, "\r\n");
    Cy_SCB_UART_PutString(UART_HW, "PING destination = ");

    for(uint8_t i=0; i<DMAC_TRANSFER_SIZE; i++)
    {
        dstdata1[i] = g_region1Dst[i];
        while (!Cy_SCB_UART_IsTxComplete(UART_HW));
        Cy_SCB_UART_Put(UART_HW, dstdata1[i]);
    }
    Cy_SCB_UART_PutString(UART_HW, "\r\n");

    /* Validate the transferred data */
    Cy_SCB_UART_PutString(UART_HW, "PONG source = ");

    for(uint32_t i=15; i<DMAC_TRANSFER_SIZE; i--)
    {
        srcdata2[i] = g_region2Src[i];
        while (!Cy_SCB_UART_IsTxComplete(UART_HW));
        Cy_SCB_UART_Put(UART_HW, srcdata2[i]);
    }
    /* Validate the transferred data */
    Cy_SCB_UART_PutString(UART_HW, "\r\n");
    Cy_SCB_UART_PutString(UART_HW, "PONG destination = ");

    for(uint32_t i=15; i<DMAC_TRANSFER_SIZE; i--)
    {
        dstdata2[i] = g_region2Dst[i];
        while (!Cy_SCB_UART_IsTxComplete(UART_HW));
        Cy_SCB_UART_Put(UART_HW, dstdata2[i]);
   }

    Cy_SCB_UART_PutString(UART_HW, "\r\n");


    Cy_SCB_UART_PutString(UART_HW, "- DMA transfer is completed. \r\n");

    for(;;)
    {
    }
}

/* [] END OF FILE */
